### ISSUE TITLE
Can't open it on macOS 12

### ISSUE THREAD

**Issue by NineXYZ** [ArmCord/ArmCord#48]
If I try to open it from the menu it tells me that it cannot be opened, if I do it from the terminal I get the following error.
> The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003ddf990 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by smartfrigde** [comment]
I have no real way of fixing this error. I don't own an mac and I have no idea how to properly package apps to it. If you find a way to get it working feel free to make a pull request or share your findings.

**Comment by NineXYZ** [comment]
I'm new to macOS and especially to arm so I have no idea... But I'll try to find a way to fix this problem.
