### ISSUE TITLE
can't open it on arch linux 5.13.10-arch1-1

### ISSUE THREAD

**Issue by Senpai-10** [ArmCord/ArmCord#49]
when i run the appImage app 
i get this error:
`zsh: exec format error: ./ArmCord-2.5.0-arm64.AppImage`

**Comment by smartfrigde** [comment]
Do you have docker installed?

**Comment by Senpai-10** [comment]
> Do you have docker installed?

Yes

**Comment by smartfrigde** [comment]
Are you sure you are on Arm64? Maybe try running any other docker image. You can always try build your own docker image. It works fine for me

**Comment by Senpai-10** [comment]
lol i downloaded the wrong file, i should have downloaded `ArmCord-2.5.0.AppImage` thank you
