### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by firezt** [ArmCord/ArmCord#52]
Hi!
I was wondering if there would be some way to make the data be stored in the root folder where the application is instead of default AppData on Windows. 

Thanks!

**Comment by smartfrigde** [comment]
It would require some tweaking but it's completely possible. I'll see what I can do later

**Comment by Kyiro** [comment]
Any updates on this one year old issue?

**Comment by smartfrigde** [comment]
Well it's easy to build a portable build, we just haven't added such option onto our CI

**Comment by Kyiro** [comment]
> Well it's easy to build a portable build, we just haven't added such option onto our CI

How can I build a portable build then?

**Comment by smartfrigde** [comment]
Follow the instructions in readme but instead of
`npm run package`
Run
`pnpm i - g electron-builder
electron-builder --windows portable`
