### ISSUE TITLE
Update app logo/icon to new Discord icon

### ISSUE THREAD

**Issue by he3als** [ArmCord/ArmCord#53]
Discord changed their logo/icon. To stay consistent with the rest of ArmCord (in the UI there is the new logo), update the app icon to the new Discord logo as well.

**Comment by he3als** [comment]
![image](https://user-images.githubusercontent.com/65787561/134028534-57611fea-42ec-4d8e-93de-6118f14a4c95.png)
As you can see (in the taskbar), there is still the old logo

**Comment by kckarnige** [comment]
![image](https://user-images.githubusercontent.com/32397453/134058987-821a541a-6aff-4144-b3c1-2ec45a9eee0c.png)

**Comment by kckarnige** [comment]
We're going to be adding our own logo in the future
