### ISSUE TITLE
Screenshare support

### ISSUE THREAD

**Issue by he3als** [ArmCord/ArmCord#54]
Hello, it would be great if ArmCord supported screensharing. You can watch other people's screenshares, but you can not screenshare yourself.

**Comment by SoloUnity** [comment]
This implementation of arm64 discord for apple silicon can screen share:
https://github.com/yannhodiesne/Discord-M1

Hope that helps

**Comment by smartfrigde** [comment]
![image](https://user-images.githubusercontent.com/37928912/140542320-98c10a72-f06e-4565-ba8d-8d58187b6c1a.png)
Next update ;)

**Comment by SoloUnity** [comment]
> ![image](https://user-images.githubusercontent.com/37928912/140542320-98c10a72-f06e-4565-ba8d-8d58187b6c1a.png)
> Next update ;)

Will there be a compiled version for apple silicon?

**Comment by smartfrigde** [comment]
I don't have a Mac/Mac OS device and the builds that were made before were broken so I'm 99% sure it won't work. See #48

**Comment by kz-n** [comment]
> I don't have a Mac/Mac OS device and the builds that were made before were broken so I'm 99% sure it won't work. See #48

See [MacOS Runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), Don't know if that counts as "Apple Silicon"

**Comment by smartfrigde** [comment]
It's not a issue with binaries produced but with the code itself not being compatible with mac os environment.

**Comment by smartfrigde** [comment]
Done in 3.0
