### ISSUE TITLE
Top left corner ArmCord text changes when loading Discord.

### ISSUE THREAD

**Issue by he3als** [ArmCord/ArmCord#55]
I am using Windows and the latest release. The top left corner ArmCord text changes when loading Discord.

When first loading ArmCord: 
![image](https://user-images.githubusercontent.com/65787561/134029027-981ce7dd-4ddd-4183-a185-89eb03031e84.png)

After loading ArmCord:
![ArmCord_RZinxpixGI](https://user-images.githubusercontent.com/65787561/134029063-15d33ad6-0e96-435e-baa0-1e959de5b7d6.png)

**Comment by smartfrigde** [comment]
See #56
