### ISSUE TITLE
Way higher memory usage with GooseMod

### ISSUE THREAD

**Issue by he3als** [ArmCord/ArmCord#57]
Without the GooseMod extension installed, ArmCord would get around 20mb to 30mb of RAM usage and very minimal CPU usage around 1% to 2% (while watching a screen share too). With GooseMod installed that RAM usage has gone up to 550mb and the CPU usage has increased. 

Is it possible to make ArmCord not depend on GooseMod (for certain features) and make it additional to fix this issue? Or is there another solution?

**Comment by smartfrigde** [comment]
In next update you won't be required to have GooseMod installed for everything to work correctly
