### ISSUE TITLE
Add the ability to disable Minimize to Tray.

### ISSUE THREAD

**Issue by Aetopia** [ArmCord/ArmCord#58]
By default ARMCord, minimizes to the tray when the Close Button is clicked/selected. If possible, add a toggle which allows to enable and this feature like in the vanilla Discord client.

![image](https://user-images.githubusercontent.com/41850963/134054741-e61ffbde-fe1d-4ec2-a189-39b36cdbf25b.png)

**Comment by DodoGames7** [comment]
Armcord uses web version of discord so i don't think lts possible

**Comment by smartfrigde** [comment]
> Armcord uses web version of discord so i don't think lts possible

It is completely possible. We plan to add it in ArmCord Helper possibly this weekend

**Comment by DodoGames7** [comment]
Got it!

**Comment by smartfrigde** [comment]
Done on main branch, you need to build from source for now to enable this or wait for next release

**Comment by UltraBlackLinux** [comment]
Where is that toggle? Phosh currently does not appear to support applications with a system-tray icon. I would like to disable this as well so that the application actually quits when I close the window. 
I've looked through all settings categories but can't find this.

**Comment by AidanJHMurphy** [comment]
If anyone else is looking for this, I found the setting under Settings > Legcord Settings > Work in background. I think this is in a different place than the stock Discord setting by necessity.
