### ISSUE TITLE
[Bug] "Cache" doesn't save.

### ISSUE THREAD

**Issue by timof121** [ArmCord/ArmCord#60]
So basically I installed ArmCord from source (I'm running Raspbian/Debian aarch64) and it works fine (except i had to put goosemod to plugins dir)
My issue is that armcord doesn't store the cache/settings after quitting. For ex, I have to login everytime I restart armcord, and the goosemod "rpc" extension settings reset after the armcord restart. Maybe I should launch/rebuild armcord as root user?

**Comment by smartfrigde** [comment]
That's 90% a GooseMod bug. If I remember correctly settings are partially broken on there.

**Comment by smartfrigde** [comment]
Not ArmCord bug.
