### ISSUE TITLE
[Bug] Javascript error after installing Armcord on Windows 11

### ISSUE THREAD

**Issue by red-star-fighter** [ArmCord/ArmCord#64]
I have a surface pro X, and have wanted a proper ARM client for discord for a long time. I ran the exe and it seemed to install just fine, but after it finished this error popped up: "...\settings.json: Unexpected end of JSON input..."
![image](https://user-images.githubusercontent.com/21150801/144079604-fa9809b8-c31f-4abc-ad12-c434701d5777.png)
The error is only one-time. Restarting the application allowed it to start successfully, and settings seem to work alrighty. the cumcord plugins tab crashed the discord page, but a reload fixed it.

**Comment by smartfrigde** [comment]
Not an issue just your laptop is so fast the json gets read too quickly lol
