### ISSUE TITLE
Issue with setup.exe 

### ISSUE THREAD

**Issue by Mor-leidr** [ArmCord/ArmCord#72]
I tried running setup.exe and all it did was just open the armcord window but nothing has happened. It did install it as a program but the window is just white.

![image](https://user-images.githubusercontent.com/67807691/150608550-a60c1da5-10a7-44e5-a449-69dc61cadbaf.png)

**Comment by kz-n** [comment]
What version are you using?
3.0.2 is the latest working version for Windows atm.

**Comment by Mor-leidr** [comment]
I just downloaded the latest exe which the releases tab said it was posted 4 days ago

**Comment by kz-n** [comment]
You should use 3.0.2 with windows at the moment

**Comment by vincentwang0905** [comment]
same
3.0.3 doesn't work on windows

**Comment by smartfrigde** [comment]
aware, use 3.0.2

**Comment by smartfrigde** [comment]
Fixed in 3.0.4
