### ISSUE TITLE
im using macOS not windows 

### ISSUE THREAD

**Issue by ImLoadingUuU** [ArmCord/ArmCord#73]
<img width="1680" alt="截圖 2022-01-29 下午7 16 16" src="https://user-images.githubusercontent.com/69704016/151658881-e913e84c-f0c3-4f64-aed3-4cec0189a40b.png">
can u change to MacOS Close,Hide,Maxium Button.

**Comment by smartfrigde** [comment]
Yeah sure I can in next version, but I have 2 questions. Does the app work well on Mac OS? Did it display any major errors? I don't have a Mac OS machine so I'm just curious.

**Comment by ImLoadingUuU** [comment]
1.Yes it work!
2.no?

**Comment by ImLoadingUuU** [comment]
ooo i found a bug,right click menu wont work!

**Comment by PoorPocketsMcNewHold** [comment]
> <img width="1680" alt="截圖 2022-01-29 下午7 16 16" src="https://user-images.githubusercontent.com/69704016/151658881-e913e84c-f0c3-4f64-aed3-4cec0189a40b.png">
> can u change to MacOS Close,Hide,Maxium Button.

[You could force ArmCord to use your native titlebar instead of their own custom one](https://github.com/ArmCord/ArmCord/wiki/How-to-change-the-titlebar%3F).

**Comment by smartfrigde** [comment]
Fixed on main branch, you need to build from source for now to enable this (native titlebar) or wait for next release
