### ISSUE TITLE
Right click (context menu) not working

### ISSUE THREAD

**Issue by matteoturini** [ArmCord/ArmCord#74]
In certain parts it works, on some it doesnt. Right clicking on a message doesn't work, but on a person on the sidebar it does.

**Comment by smartfrigde** [comment]
try using importing our helper plugin into cumcord import plugin box https://helper.smartfridge.space/ 
![obraz](https://user-images.githubusercontent.com/37928912/152317438-e6c07029-c54d-4319-bf0a-70e82022f781.png)

**Comment by jsmoment** [comment]
> try using importing our helper plugin into cumcord import plugin box https://helper.smartfridge.space/ ![obraz](https://user-images.githubusercontent.com/37928912/152317438-e6c07029-c54d-4319-bf0a-70e82022f781.png)

i have this issue as well, the helper plugin did not help

**Comment by smartfrigde** [comment]
Well let's start with fact Electron not having right click action built in. Discord doesn't have one enabled on browsers too. The helper plugin tries to patch it back in. I'm gonna see what I can do and hopefully fix this

**Comment by KibSquib48** [comment]
any updates on this?

**Comment by smartfrigde** [comment]
Fixed on main branch, you need to build from source for now to enable this or wait for next release
