### ISSUE TITLE
Plugin auto importer

### ISSUE THREAD

**Issue by Mrbroggle** [ArmCord/ArmCord#78]
It would be a good idea that when you install your armcord it pulls all your goosemod and betterdiscord plugins into goosemod would make transferring to

**Comment by lexisother** [comment]
This is hardly possible? How is it supposed to just magically know what plugins you have installed on another client?

**Comment by Mrbroggle** [comment]
> Also, ArmCord can't "pull in" BD plugins. It doesn't even support BD plugins.
GooseMod uses the better discord plugin repo

> This is hardly possible. How is it supposed to just magically know what plugins you have installed on another client?
You can look at files or make a backup of the normal clients GooseMod then import it

**Comment by lexisother** [comment]
> GooseMod uses the better discord plugin repo

Literally not true.

> You can look at files or make a backup of the normal clients GooseMod then import it

You cannot. GooseMod stores no local files.

**Comment by CanadaHonk** [comment]
BD and GM have no relation, or plugin compatibility.

**Comment by smartfrigde** [comment]
Not possible without doing unnecessary hacky solution

**Comment by CanadaHonk** [comment]
If you're using GM you can just use the backup system anyway
