### ISSUE TITLE
Uninstaller doesn't delete user data

### ISSUE THREAD

**Issue by xTunio** [ArmCord/ArmCord#79]
Uninstaller on Windows doesn't remove user data, preventing from further changes to installation.
Explainer video of the issue: https://www.youtube.com/watch?v=3zqwuq6ywsw

**Comment by lexisother** [comment]
Intended behaviour. File a report at the Electron repository.

**Comment by smartfrigde** [comment]
The changes can be done by directly editing the config file or using the settings that are gonna be present in next update
