### ISSUE TITLE
Can't switch from fosscord

### ISSUE THREAD

**Issue by EmbukuN** [ArmCord/ArmCord#81]
In the Linux x86_64 Debian version, I mistakenly and rather foolishly chose fosscord during the initial setup. Now, the whole thing is very broken and I'm unable to sign back into my account. So I want to go through the armcord setup again and have tried every method but I can't re-do the initial setup in any way, shape or form. Immediate assistance is requested, effective immediately. (please?)

**Comment by smartfrigde** [comment]
Sorry for responding so late. You can find config files in `~/.config/ArmCord/storage`. There should be settings.json. Modify it or delete it to trigger initial setup
