### ISSUE TITLE
Support for unread message count badge on taskbar

### ISSUE THREAD

**Issue by DoKM** [ArmCord/ArmCord#83]
Definetly a Request.

Implement the unread messages badge on the taskbar icon as in the normal discord client.
Makes it a lot easier to multitask without having to check if you get a new message and also makes sure the client isnt missing any features compared to the default discord client

And maybe the ability to change the defualt icon to something else? It might be just me but its a tad hard to spot compared to the discord logo.

**Comment by smartfrigde** [comment]
Added to tray in latest commit, check out latest dev build

**Comment by Yenof** [comment]
Hi, I would still prefer this feature to be in the taskbar instead of the tray.

**Comment by smartfrigde** [comment]
> Hi, I would still prefer this feature to be in the taskbar instead of the tray.      
@Yenof    

Enable dynamic icon in ArmCord settings (unless you're using Microsoft Store build then it's unsupported there)
