### ISSUE TITLE
minimum modded client support

### ISSUE THREAD

**Issue by EmbukuN** [ArmCord/ArmCord#87]
I'm only able to choose between goosemod, cumcord, and a third alternative that I don't even remember its name. I can't install betterdiscord in any way, shape, or form. Immediate assistance is requested. (please?) Btw, legcord is very broken.

**Comment by smartfrigde** [comment]
You can't install BetterDiscord in ArmCord. Legcord doesn't support Windows

**Comment by sourcekilla** [comment]
bur bd web exists?

**Comment by smartfrigde** [comment]
Where?

**Comment by sourcekilla** [comment]
https://github.com/Strencher/BdBrowser

**Comment by smartfrigde** [comment]
You can install this by dropping it into %appdata%\ArmCord\plugins

**Comment by MattTheTekie** [comment]
how? nothing happens.

**Comment by smartfrigde** [comment]
Pretty sure BdBrowser has been abandoned by it's creator so there's not much help I can provide in that

**Comment by rollingmoai** [comment]
https://github.com/tsukasa/BdBrowser
