### ISSUE TITLE
Adoption of custom keybinds (not supported in web version)

### ISSUE THREAD

**Issue by rpcarvalheira** [ArmCord/ArmCord#88]
![image](https://user-images.githubusercontent.com/60274770/160359753-038d44ec-181c-4a1e-aef0-77173d8f3251.png)

Latest setup, tried with all discord versions, also tried with cumcord and goosemod. Not being able to use custom keybinds screws me in a huge way :/

Is it possible to adapt only this thing? Custom settings like toggle mute are rather important to me, so it could be awesome if armcord supports it.

**Comment by PoorPocketsMcNewHold** [comment]
Probably better to rename the issue to something more descriptive. As explain in the FAQ, ArmCord is based to the web version, not from a decompiled app version for example, so those features aren't “automatically” supported from the get-go, some proprietary features like Discord local game RPC aren't supported on ArmCord for example.
Nonetheless, still worth asking if native Custom Keybinds could be implemented if it isn't just an issue on your end.

**Comment by rpcarvalheira** [comment]
Fair enough, changing.

**Comment by orowith2os** [comment]
I'd like to note that, on Linux, xdg-desktop-portal merged support for global keybinds (v1.16), so keybinds should work on Wayland.

I *think* using xdg-desktop-portal removes the need of capturing keybinds specific to X11, too, but not entirely sure on that.

**Comment by MajliTech** [comment]
its 2 years since this started, on KDE Wayland this still doesn't work.

**Comment by smartfrigde** [comment]
@MajliTech Maybe try to contribute? I would be happy to merge this feature into the codebase ;)

**Comment by MajliTech** [comment]
> @MajliTech Maybe try to contribute? I would be happy to merge this feature into the codebase ;)

could try, don't know how. please don't get me as a complaining person

**Comment by smartfrigde** [comment]
![image](https://github.com/user-attachments/assets/72f68dd5-38e9-4fbd-8cbc-9a00d12b4483)
![image](https://github.com/user-attachments/assets/c11732de-4e89-45d7-800f-b61001d7b5f8)
Implemented with latest [devbuilds](https://github.com/ArmCord/ArmCord/releases/tag/devbuild), both global and local keybinds can be added now.
